# Generated by Django 3.0 on 2020-10-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('landline', models.CharField(max_length=200)),
                ('Bank_id', models.CharField(max_length=200)),
                ('Bank_Name', models.CharField(max_length=200)),
                ('opening_credit', models.FloatField()),
                ('opening_debit', models.FloatField()),
                ('ntn', models.CharField(max_length=200)),
                ('cnic', models.CharField(max_length=200)),
                ('JoiningDate', models.DateField(auto_now=True)),
                ('Address', models.CharField(max_length=200)),
                ('current_cr', models.FloatField()),
                ('current_dr', models.FloatField()),
                ('licensce_number', models.CharField(max_length=200)),
                ('expairy_date', models.DateField(auto_now_add=True)),
                ('security_check', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account_Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account_Category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account_Type')),
            ],
        ),
    ]
