# Generated by Django 3.0 on 2020-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='JoiningDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='expairy_date',
            field=models.DateField(),
        ),
    ]
